### ISSUE TITLE
Tablet mode on Android N

### ISSUE THREAD

**Issue by andreiluca** [maxpower47/PinDroid#53] opened 2016-07-11 17:05 UTC
When I set the display size in Android N DP4 to small it goes to tablet mode. Likely wrong DPI setup.
Thank you for the awesome Pinboard client and keep up the good work!

**Comment by materemias** [comment] 2016-08-27 18:50
Having a preference to force phone layout or tablet layout would be great

**Comment by kLy** [comment] 2016-09-07 07:51
Yes this would be really useful! As it is things get displayed with half the screen size:
https://goo.gl/photos/RUGgZNJaJcPRGTm57

**Comment by materemias** [comment] 2016-11-12 09:10
Duplicate of #62

**Closed** 2016-11-14 12:43 UTC
