### ISSUE TITLE
Share to Read Later asks for account every time on Marshmallow

### ISSUE THREAD

**Issue by polm** [maxpower47/PinDroid#41] opened 2015-10-24 15:23 UTC
Not sure if this is related to #34 or not, but with Marshmallow on a Nexus5, every time I share to Read Later it asks me to choose an account even though I only have one account configured. The dialog that pops up has "[my account]" and "Add New Account" options. Is this the expected behavior?

**Comment by wenLiangcan** [comment] 2015-10-25 01:30
Same on Nexus 7.

**Comment by jzaefferer** [comment] 2015-12-02 00:49
Same here, with Android 6 on Nexus 5. 

I tried the standalone read later app mentioned in the readme as a workaround, didn't help.

**Comment by chastell** [comment] 2016-01-21 18:58
For what it's worth I have the same issue on Nexus 5X with Android 6.0.1. Also #40 is a duplicate of this.

**Comment by alerque** [comment] 2016-01-23 18:26
This started happening to me too when I upgraded to a Marshmallow based ROM.

**Comment by chastell** [comment] 2016-01-24 08:44
FWIW, this doesn't happen with there regular short-cut - so it's actually faster to share with Pinboard, save, back (as the 'choose an account' modal takes a lot of time to show up).

**Comment by jfisbein** [comment] 2016-02-22 18:10
Same on Nexus 5x

**Comment by maxpower47** [comment] 2016-02-26 20:18
This is fixed in b0b71e650d516d261760c05d7a932548f2a7ac67.  

3.1.1 has been published to the play store and will be available shortly.

**Closed by maxpower47** 2016-02-26 20:18 UTC

**Comment by jzaefferer** [comment] 2016-02-27 00:35
Nice! Thank for a great app, now I can enjoy the read later share option, too.

**Comment by polm** [comment] 2016-02-27 06:36
Thanks! Was able to confirm this worked on my Nexus5.
